### PR TITLE
update log format to text from json

### PR DESCRIPTION
**Pull request by nsuma8989**

### CODE REVIEW

**Review by jeremybumsted — COMMENTED** [review]
@nsuma8989 I like this idea, I wonder if it would make more sense to have it default to text and we can allow people to specify any output type (maybe they prefer some other format) as an option. I don't think it would matter to us what format we get them in, but they might like to have them a certain way?

**Comment by nsuma8989** [comment]
@jeremybumsted Yes, having option of output type makes sense with default to text. I can amend this pull request with that approach.

**Comment by nsuma8989** [comment]
@jeremybumsted Added output format flag with text format as default option

**Review by jeremybumsted — APPROVED** [review]
Amazing!

**Pull request merged**
